digitalocean/do-agent

Makefile

updating text associated with release tagging.

Update text in makefile

---

cmd/do-agent/main.go

-Valid targets with valid timestamps are only available for a period after the new agent package has been deployed. When an valid agent that has an expired timestamp is encountered it should not create an error message. This log entry created by this condition has been modified.

Remove tuf target expiration errors from the logs.

---

AUTHORS
Makefile
README.md

This PR adds a few minor improvements for first time contributors on the project, so there is a nice experience on a fresh checked out repository.
Each commit has detailed messages on the pitfalls I faced when I first tried to build and test locally.

First time commiter improvements

---

Dockerfile
Makefile
README.md
cmd/do-agent/main.go
procfs/diskstats.go
procfs/loadavg.go
procfs/meminfo.go
procfs/meminfo_test.go
procfs/mounts.go
procfs/netdev.go
procfs/osrelease.go
procfs/path.go
procfs/stat.go
vendor/vendor.json

This patch set enables running the agent in a Docker container.

Docker: allow agent to run in container.

---

update/update.go

Cycled the root tuf key. This updates clients to trust the latest key.

Update the root.json key

---

Dockerfile

This should fix issues #51 and #54

Add ca-certificates to docker image

---

.travis.yml
Makefile
scripts/deploy.sh

deployments to apt/yum will be moved to internal process
with the new self-hosted repositories

fix/deploy/only push to GitHub

---

cmd/do-agent/config.go
scripts/uat.sh

WIP until we get the finalized doKubeEndpoint URL to embed

IN-2171: enable DO K8s scraper

---

Makefile
packaging/scripts/after_install.sh

feat: use dedicated user

---

scripts/deploy.sh
scripts/uat.sh

uat: add command_bin_version
deploy: post stage to slack

fix promote_docker

---

cmd/do-agent/config.go

use a string instead of bool to configure where scraping of kubernetes metrics is performed.

use url endpoint instead of bool for k8s metrics

---

cmd/do-agent/config.go
k8s-daemonset.yml
pkg/collector/scraper.go
pkg/collector/scraper_test.go

Removed scraper assumption that metrics are located at /metrics

updates k8s flag to k8s-metrics-path.

---

cmd/do-agent/config.go
cmd/do-agent/whitelist.go

Postgres scrape

---

scripts/uat.sh

rename commands:
delete -> destroy
versions -> version
boot_status -> init_status
also remove extraneous USER_DATA since we don't use it

uat: use image IDs, rename some commands

---

scripts/update.sh

Fixes #150

---

cmd/do-agent/config.go
pkg/clients/tsclient/client.go

This is primarily for testing. The values will be overridden by the server on first write.

allow overriding sonar limits for testing

---

packaging/scripts/after_install.sh
packaging/scripts/after_remove.sh
scripts/install.sh

fix deb postrm

---

cmd/do-agent/config.go
internal/process/collector.go
pkg/decorate/topk.go
pkg/decorate/topk_test.go

Turns on process collection. 
Only returns the Top K processes to reduce metrics

Feat/in 2565/top processes

---

Dockerfile
Makefile

[strips extra symbols](https://golang.org/cmd/link/) and use distroless docker image for a smaller footprint

use -w -s ldflags and distroless docker image

---

cmd/do-agent/aggregation.go
cmd/do-agent/config.go

Fix/in 2598/k8s aggregation

---

scripts/install.sh

Small typo fix for the install script. Thanks for making this open source! :)

Fix typos in install.sh

---

scripts/upgrade-droplets.sh

support owned user

---

Makefile
cmd/do-agent/config.go
pkg/clients/tsclient/client.go

* Update auth and radar endpoints
* Add phony install_deb package for convenience

Update auth and radar endpoints

---

Makefile
cmd/do-agent/config_filesystem.go

ignoring /boot is a potential fix for #233

Ignore boot mountpoint

---

internal/log/log.go

#263: use syslog log facility intead of default kern

---

Makefile

The recent changes to the makefile broke the docker build. Moving all of the required variable, macros and target into the Makefile fixes the issue.

fix: docker build through makefile

---

packaging/scripts/after_install.sh

Remove keyring pulling from agent post-install scripts.

chore: cleanup post-install script

---

cmd/do-agent/aggregation.go
cmd/do-agent/config.go
cmd/do-agent/whitelist.go

cc: @leoxlin and @mdanzinger for context. Do not merge yet until we have verified that the metrics from agent are scrapable.

enable mongodb metrics collection and whitelisting

---

cmd/do-agent/aggregation.go
cmd/do-agent/whitelist.go

This is the name of the metrics emitted by mongoagent

[MONGO-2724] Correctly whitelist metrics for mongo
