README.md

Fixes `chown: invalid group: ‘nobody:nobody’` on reinstallation.
cc @cagedmantis @imchairmanm

Use `apt-get purge` to avoid reinstallation bug

---

cmd/do-agent/main.go

Properly handle error when the local repository is not updated with the latest timestamp.

Additional Log cleanup

---

procfs/netdev.go
procfs/netdev_test.go

While parsing network metrics found in /proc/netdev, interfaces would be ignored if there wasn't a space between the interface + colon and the received bytes.

Fix a bug where the netdev metrics would be ignored.

---

collector/file_system.go
collector/filter.go

- fixes an issue with double-reporting root that happens with Docker
- fixed comments
By filtering non-block psuedo filesystems, metric reporting dropped between 50-75% of the time. I want to clean this up dropping this in favor of a more dynamic check (i.e. look if the filesystem is backed by a block device?)

filter refinement: filter on both file-systems and devices

---

cmd/do-agent/main.go
monitoringclient/monitoringclient.go

Here's an example of the metadata service being stubbed out for use in our tests:
doagent logs:
doagent 2017-03-16T18:51:01 UNK 2017/03/16 18:51:01 Do-Agent version dev
doagent 2017-03-16T18:51:01 UNK 2017/03/16 18:51:01 Do-Agent build metadata-override.8748c5d
doagent 2017-03-16T18:51:01 UNK 2017/03/16 18:51:01 Architecture: amd64
doagent 2017-03-16T18:51:01 UNK 2017/03/16 18:51:01 Operating System: linux
doagent 2017-03-16T18:51:01 UNK 2017/03/16 18:51:01 Metadata URL Override: http://metadatastub
doagent 2017-03-16T18:51:01 UNK 2017/03/16 18:51:01 Authentication URL Override: http://radar:8081
doagent 2017-03-16T18:51:01 UNK 2017/03/16 18:51:01 Metrics URL Override: http://wharf:8082
doagent 2017-03-16T18:51:01 UNK 2017/03/16 18:51:01 Checking for newer version of do-agent
stubbed …

allow override of metadata url

---

log/log.go

This moves logging from the kernel target (default for GoLang) to the syslog target.

Correct log priority

---

Makefile
packaging/scripts/after_install.sh

keep do-agent out of the PATH to prevent any accidental executions

/usr/local/bin/do-agent -> /opt/digitalocean/bin/do-agent

---

cmd/do-agent/config.go
internal/flags/flags.go
scripts/uat.sh

previous definition was not working and `--no-collector.<flag>` is consistent with the [node_exporter](https://github.com/prometheus/node_exporter) flags.

move no-collector.processes flag to be consistent

---

scripts/update.sh

Instead of running a brute force update to all repositories this restricts the update
to only the source file that is used by do-agent.

only update do-agent repository in update.sh

---

packaging/scripts/after_install.sh
packaging/scripts/before_install.sh
scripts/install.sh
scripts/uat.sh

The user needs to exist before the installation because the packages reference it

create user in before_install.sh

---

scripts/install.sh
scripts/uat.sh
scripts/update.sh

install.sh: 
* fixed an issue where apt-get update would cause install to fail if some repositories aren't available which shouldn't block installing.
* fixed an issue with debian where apt-get install would fail because apt-transport-https package wasn't installed
* only update agent repository after installing the sources.list.d
uat.sh:
* use the official install.sh script
* add boot_status command to check the status of the cloud-init boot
* print the image name in the output message of `create` which sometimes results in `null` when the create fails

Install fix

---

cmd/do-agent/config.go
pkg/collector/scraper.go
pkg/collector/scraper_test.go

Currently DOKS clusters that do not have kube-state-metrics installed (the default) end up emitting a pretty fair volume of error logs since the scraping fails.
This PR introduces the ability to inject a custom log level to the scraper on initialization (also moves timeouts to this pattern) and configures the kubernetes scraper to use the debug log level.
Not sure if this is the approach/pattern that you folks would like to adopt, so feel free to reject/change as you prefer.

Scraper custom log level

---

cmd/do-agent/config.go
cmd/do-agent/config_test.go
pkg/decorate/labels.go
pkg/decorate/labels_test.go

Supports --additional-label flag which parses values in the format of key:value and uses them as label pair for all metrics.

Feat/in 2408/additional labels

---

Makefile
packaging/etc/init/do-agent.conf
packaging/etc/systemd/system/do-agent.service
packaging/scripts/after_install.sh
scripts/update.sh

allows users to customize init scripts without losing changes on update

don't override init files on update

---

scripts/install.sh

The install script should be considered a sledge hammer. Anyone running the script should expect it to override any configuration files. Switching from remove to purge will do that.

use apt-get purge when using install.sh to prevent config issues

---

cmd/do-agent/config.go

Did a quick org-wide search for instances of DOK8s and this was one.

Replace DOK8s with DOKS in config.go

---

README.md

The `do-agent` command is spelled incorrectly.

Fix typo in readme: aegnt -> agent

---

.gitignore
cmd/do-agent/config.go
go.mod
pkg/clients/roundtrippers/bearer_token.go
pkg/clients/roundtrippers/bearer_token_file.go
pkg/clients/roundtrippers/bearer_token_file_test.go
pkg/clients/roundtrippers/bearer_token_test.go
pkg/clients/roundtrippers/testdata/token
pkg/clients/roundtrippers/utils.go
pkg/collector/scraper.go

This PR adds support for scraping kube-state-metrics behind an authentication proxy (kube-rbac-proxy) by leveraging bearer token authentication.  
Bearer tokens can either be passed in directly through the `--bearer-token` flag, or dynamically read with the `--bearer-token-file` flag.  
#224

feat: add support for bearer_token auth

---

cmd/do-agent/config.go

This PR increases the default scrape timeout to account for very large `kube-state-metrics` targets.

increase scrape timeout

---

scripts/install.sh

Added AlmaLinux OS (1:1 binary compatible fork of RHEL) to the Supported Operating System.
Moved to Officially Unsupported OS as per the comment in the PR-251 by @bsnyder788

Added AlmaLinux OS Support

---

cmd/do-agent/aggregation.go
cmd/do-agent/whitelist.go

Update metrics whitelist for dbaas: 
- Makes additions to all engines (MySQL, Redis, PG) -metrics for cluster health monitoring  and telemetry
- Initializes Kafka metrics

update dbaas metrics, all engines

---

cmd/do-agent/whitelist.go

Update `postgresql_database_size_database_size` metric on whitelist. Remove trailing space in metric name.

update pg database size metric name

---

cmd/do-agent/aggregation.go

Kafka collected metrics use capitalized letters in their names. That created an issue with data aggregation for the newly created metrics.

fix: kafka metrics aggregation

---

deploy/do-agent.yaml

The node selector `beta.kubernetes.io/os` is deprecated and it is recommended to use `kubernetes.io/os`.

fix: change k8s node selector to `kubernetes.io/os`

---

packaging/scripts/install.sh

Under Ubuntu22 and debian bullseye (stable) warnings are issued every time `apt-get update` is run: 
> W: https://repos.insights.digitalocean.com/apt/do-agent/dists/main/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
This PR alters the do-agent install.sh script to follow the pattern used in the [droplet-agent install script](https://github.com/digitalocean/droplet-agent/blob/dde65fb2002d6e19677750fb689ea7ab27f11c62/packaging/scripts/install.sh#L160) to not use
`apt-key` because `apt-key` and `/etc/apt/trusted.gpg` are deprecated in Ubuntu22 and Debian bullseye.
Related [DO Community Question](https://www.digitalocean.com/community/questions/digitalocean-agent-key-deprecation-warning-in-ubuntu-22-04-jamm …

Stop using apt-key (fixes Ubuntu 22 warnings)

---

go.mod

A request smuggling attack is possible when using MaxBytesHandler. When using MaxBytesHandler, the body of an HTTP request is not fully consumed. When the server attempts to read HTTP2 frames from the connection, it will instead be reading the body of the HTTP request, which could be attacker-manipulated to represent arbitrary HTTP2 requests.
The product acts as an intermediary HTTP agent (such as a proxy or firewall) in the data flow between two entities such as a client and server, but it does not interpret malformed HTTP requests or responses in ways that are consistent with how the messages will be processed by those entities that are at the ultimate destination.
```js
package main
import (
"fmt"
"io"
"log"
"net/http"
"runtime"
"golang.org/x/net/http2"
"golang.org/x/net/http2/h2c"
) …
```

Patched Fix http2 vulnerable to request smuggling attack

---

internal/log/log.go
pkg/collector/node.go

Use a non-noop logger in debug mode so we can see the logs from the collectors.

Support collector logging in debug mode

---

packaging/scripts/after_install.sh

`userdel` was added to the after_install script to re-create users without a shell. The update has run, we can now remove the deletion.

chore: remove userdel from after_install.sh

---

Makefile

CGO builds are causing the binaries to be non-launchable on more dated OS images. This change disables CGO to prevent portability issues.

fix: disable cgo
